all:
	convert +append tile_desert_hill.png tile_grass.png tile_mountain.png tile_ocean.png tile_shallow_ocean.png tile_tundra.png civ.png
	convert civ.png PNG8:civ-indexed.png
	mv civ-indexed.png ../assets-img/civ.png
